---
  - name: "Execute jenkins.py"
    hosts: localhost
    connection: local
    tasks:

    - name: "Execute python file"
      command: python3 helloworld.py
      register: output

    - debug: var=output.stdout_lines
       msg: "{{ extra_vars_key }}"
